language: generic

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: Bionic
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
  fast_finish: true

before_install:
  - chmod +x Build/travis-push.sh
script:
  - pwsh -File './Build/enableExperimentalFeature.ps1'
  - pwsh -File './Build/build.ps1'
after_success:
  - '[ "${TRAVIS_EVENT_TYPE}" = "push" ] && [ "${TRAVIS_BRANCH}" = "master" ] && Build/travis-push.sh'